spring.application.name: prezentatr
metrics.path.app: prezentatr
stubrunner:
  use-microservice-definitions: true
  stubs:
    repository.root: "http://nexus.uservices.pl:8081/nexus/content/repositories/releases/"
